apiVersion: v1
kind: Secret
metadata:
  name: hollaex-kit-secret
  namespace: hollaex-kit
type: Opaque
stringData:
  ACTIVATION_CODE: ''
  API_KEY: ''
  API_SECRET: ''
  DB_HOST: 'hollaex-kit-prod-db'
  DB_NAME: 'hollaex'
  DB_PASSWORD: 'my-secure-db-password'
  DB_PORT: '5432'
  DB_USERNAME: 'hollaex'
  PUBSUB_HOST: 'hollaex-kit-prod-redis'
  PUBSUB_PASSWORD: 'my-secure-redis-password'
  PUBSUB_PORT: '6379'
  REDIS_HOST: 'hollaex-kit-prod-redis'
  REDIS_PASSWORD: 'my-secure-redis-password'
  REDIS_PORT: '6379'
  SECRET: 'my-secure-secret'
  SMTP_PASSWORD: ''
