{{- if eq .Values.job.enable false }}

kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{.Release.Name}}
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  ports:
  - name: port
    port: 10010
    targetPort: 10010
  - name: websocket-port
    port: 10080
    targetPort: 10080
  - name: plugins-port
    port: 10011
    targetPort: 10011
  selector:
    app: {{.Release.Name}}

{{- end }}


