apiVersion: v1
appVersion: 1.8.0
description: Scalable datastore for metrics, events, and real-time analytics.
home: https://www.influxdata.com/time-series-platform/influxdb/
keywords:
- influxdb
- database
- timeseries
- influxdata
maintainers:
- email: rawkode@influxdata.com
  name: rawkode
- email: giacomo@influxdata.com
  name: gitirabassi
- email: urakiny@gmail.com
  name: aisuko
- email: naseem@transit.app
  name: naseemkullah
name: influxdb
sources:
- https://github.com/influxdata/influxdb
version: 4.8.9
